kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: microservices-cluster

nodes:
- role: control-plane
  extraPortMappings:

  - containerPort: 30081
    hostPort: 30081
    protocol: TCP

  - containerPort: 30082
    hostPort: 30082
    protocol: TCP

  - containerPort: 30090
    hostPort: 30090
    protocol: TCP

  - containerPort: 30300
    hostPort: 30300
    protocol: TCP
